export interface StandardItem {
  name: string;
  unitOfMeasure: string;
  category: string;
}

/**
 * Full construction material/fixture catalog (matches SiteWise's standard
 * item list). Shared by seed.ts (fresh databases) and backfill-items.ts
 * (adding to existing organizations without touching their other data).
 */
export const STANDARD_ITEMS: StandardItem[] = [
  { name: "Cement", unitOfMeasure: "BAG", category: "Structural" },
  { name: "Sand", unitOfMeasure: "CUBIC_METER", category: "Structural" },
  { name: "Aggregate", unitOfMeasure: "CUBIC_METER", category: "Structural" },
  { name: "Bricks", unitOfMeasure: "NUMBER", category: "Structural" },
  { name: "Concrete", unitOfMeasure: "CUBIC_METER", category: "Structural" },
  { name: "Steel reinforcement bars", unitOfMeasure: "KILOGRAM", category: "Structural" },
  { name: "Timber", unitOfMeasure: "CUBIC_METER", category: "Finishing" },
  { name: "Plywood", unitOfMeasure: "SQUARE_METER", category: "Finishing" },
  { name: "Blocks", unitOfMeasure: "NUMBER", category: "Structural" },
  { name: "Paint", unitOfMeasure: "LITER", category: "Finishing" },
  { name: "Glass", unitOfMeasure: "SQUARE_METER", category: "Finishing" },
  { name: "Aluminum", unitOfMeasure: "KILOGRAM", category: "Finishing" },
  { name: "Tiles", unitOfMeasure: "SQUARE_METER", category: "Finishing" },
  { name: "Pipes", unitOfMeasure: "METER", category: "Plumbing" },
  { name: "Nails", unitOfMeasure: "KILOGRAM", category: "Hardware" },
  { name: "Gypsum board", unitOfMeasure: "SQUARE_METER", category: "Finishing" },
  { name: "Bitumen", unitOfMeasure: "KILOGRAM", category: "Structural" },
  { name: "Stone", unitOfMeasure: "CUBIC_METER", category: "Structural" },
  { name: "Lime", unitOfMeasure: "KILOGRAM", category: "Structural" },
  { name: "Plumbing fittings", unitOfMeasure: "NUMBER", category: "Plumbing" },
  { name: "Electrical wires", unitOfMeasure: "METER", category: "Electrical" },
  { name: "Doors", unitOfMeasure: "NUMBER", category: "Finishing" },
  { name: "Windows", unitOfMeasure: "NUMBER", category: "Finishing" },
  { name: "Foam insulation", unitOfMeasure: "SQUARE_METER", category: "Finishing" },
  { name: "Rubber", unitOfMeasure: "KILOGRAM", category: "Finishing" },
  { name: "Copper", unitOfMeasure: "KILOGRAM", category: "Electrical" },
  { name: "Fabric", unitOfMeasure: "SQUARE_METER", category: "Finishing" },
  { name: "Surkhi", unitOfMeasure: "KILOGRAM", category: "Structural" },
  { name: "White cement", unitOfMeasure: "KILOGRAM", category: "Structural" },
  { name: "Asphalt", unitOfMeasure: "KILOGRAM", category: "Structural" },
  { name: "Bamboo", unitOfMeasure: "METER", category: "Structural" },
  { name: "Alloy", unitOfMeasure: "KILOGRAM", category: "Structural" },
  { name: "Ceramics", unitOfMeasure: "SQUARE_METER", category: "Finishing" },
  { name: "Carbon fiber", unitOfMeasure: "KILOGRAM", category: "Structural" },
  { name: "Liquid waterproofing gel", unitOfMeasure: "LITER", category: "Finishing" },
  { name: "Toilet", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Wash basin", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Sink", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Bathtub", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Showerhead", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Hand shower", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Health faucet/Jet spray", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Cistern flush tank", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Toilet seat cover", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Bidet", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Urinal", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Flushing cistern", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Basin faucet", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Bathtub faucet", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Basin bottle trap", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Floor drain", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Shower drain channel", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Basin coupling", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Soap dish", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Towel ring", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Toilet paper holder", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Tumbler holder", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Shelf tray", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Robe hook", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Vanity unit", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Mirror", unitOfMeasure: "NUMBER", category: "Sanitaryware" },
  { name: "Exhaust fan", unitOfMeasure: "NUMBER", category: "Electrical" },
  { name: "Water heater", unitOfMeasure: "NUMBER", category: "Electrical" },
  { name: "Pipe", unitOfMeasure: "METER", category: "Plumbing" },
  { name: "Pipe fittings", unitOfMeasure: "NUMBER", category: "Plumbing" },
  { name: "Water pump", unitOfMeasure: "NUMBER", category: "Plumbing" },
  { name: "Electrical wire 0.5 sqmm", unitOfMeasure: "METER", category: "Electrical" },
  { name: "Electrical wire 0.75 sqmm", unitOfMeasure: "METER", category: "Electrical" },
  { name: "Electrical wire 1.0 sqmm", unitOfMeasure: "METER", category: "Electrical" },
  { name: "Electrical wire 1.5 sqmm", unitOfMeasure: "METER", category: "Electrical" },
  { name: "Electrical wire 2.5 sqmm", unitOfMeasure: "METER", category: "Electrical" },
  { name: "Electrical wire 4.0 sqmm", unitOfMeasure: "METER", category: "Electrical" },
  { name: "Electrical wire 6.0 sqmm", unitOfMeasure: "METER", category: "Electrical" },
  { name: "Electrical wire 10.0 sqmm", unitOfMeasure: "METER", category: "Electrical" },
  ...["15mm", "20mm", "25mm", "32mm", "40mm", "50mm", "65mm", "80mm", "100mm", "150mm"].map((size) => ({
    name: `CPVC pipe ${size}`,
    unitOfMeasure: "METER",
    category: "Plumbing",
  })),
  ...["15mm", "20mm", "25mm", "32mm", "40mm", "50mm"].map((size) => ({
    name: `CPVC elbow ${size}`,
    unitOfMeasure: "NUMBER",
    category: "Plumbing",
  })),
  ...["15mm", "20mm", "25mm", "32mm", "40mm", "50mm"].map((size) => ({
    name: `CPVC tee ${size}`,
    unitOfMeasure: "NUMBER",
    category: "Plumbing",
  })),
  ...["15x20mm", "20x25mm", "25x32mm", "32x40mm", "40x50mm"].map((size) => ({
    name: `CPVC reducer ${size}`,
    unitOfMeasure: "NUMBER",
    category: "Plumbing",
  })),
  ...["15mm", "20mm", "25mm", "32mm", "40mm", "50mm"].map((size) => ({
    name: `CPVC coupler ${size}`,
    unitOfMeasure: "NUMBER",
    category: "Plumbing",
  })),
  ...["15mm", "20mm", "25mm", "32mm", "40mm", "50mm"].map((size) => ({
    name: `CPVC union ${size}`,
    unitOfMeasure: "NUMBER",
    category: "Plumbing",
  })),
  ...["15mm", "20mm", "25mm", "32mm", "40mm", "50mm"].map((size) => ({
    name: `CPVC ball valve ${size}`,
    unitOfMeasure: "NUMBER",
    category: "Plumbing",
  })),
];
